on:
  workflow_dispatch:
    inputs:
      location:
        description: 'location'
        required: false
        default: 'azure'
    
jobs:
  my-job:
    name: Deploy gosimplehttpserver
    runs-on: ubuntu-latest
    steps:
      - name: ssh docker deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSHHOST }}
          username: ${{ secrets.SSHUSERNAME }}
          key: ${{ secrets.SSHKEY }}
          port: ${{ secrets.SSHPORT }}
          script: |
            docker pull docker.pkg.github.com/wlanboy/goservice/goservice:latest
            docker stop goservice
            docker rm goservice
            docker run --name goservice -d -p 8000:8000 docker.pkg.github.com/wlanboy/goservice/goservice:latest
